### ISSUE TITLE
Метрополитен_1

### ISSUE THREAD

**Issue by Murka325** [Murka325/HomeworkMurka#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Класс Station
- А где у тебя второй конструктор, который на вход принимает список пересадок?
- Что-то я не вижу остальных пустых методов, которые тоже нужно было добавить.

Класс Metro
- То же самое, куда-то пропала часть методов со схемы.

Класс Line
- 64 строка. Вот это ты, конечно, придумал) Нет, здесь не нужно генерировать вспомогательные списки станций, нужно просто вернуть поле класса - stations.

**Comment by vdetstvepil** [comment]
Поправь косяки и тогда зачту.

**Comment by Murka325** [comment]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Принято.
