### ISSUE TITLE
AutoPark

### ISSUE THREAD

**Issue by Murka325** [Murka325/HomeworkMurka#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- 47 строка. Нужно было переопределить метод, а не сделать его виртуальным. Просто напиши public override string ToString(). Во всех остальных методах тоже нужно поправить этот косяк. Поправишь и зачту.

**Comment by vdetstvepil** [comment]
И в readme.md своего репозитория укажи, пожалуйста, свою фамилию и имя.

**Comment by Murka325** [comment]
Исправил, вроде...

**Comment by Murka325** [comment]
@vdetstvepil вроде исправил...

**Comment by vdetstvepil** [comment]
Принято.
